/*
 * Copyright (c) 2022 Nordic Semiconductor ASA
 *
 * SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
 */

#include <zephyr/net/wifi_mgmt.h>

enum net_event_wifi_ext_cmd {
	NET_REQUEST_WIFI_CMD_ATTACH = NET_REQUEST_WIFI_CMD_IFACE_STATUS + 1,
	NET_REQUEST_WIFI_CMD_ADD_NETWORK,
	NET_REQUEST_WIFI_CMD_CLEAR_NETWORKS,
};

#define NET_REQUEST_WIFI_ATTACH				\
	(_NET_WIFI_BASE | NET_REQUEST_WIFI_CMD_ATTACH)

NET_MGMT_DEFINE_REQUEST_HANDLER(NET_REQUEST_WIFI_ATTACH);

#define NET_REQUEST_WIFI_ADD_NETWORK				\
	(_NET_WIFI_BASE | NET_REQUEST_WIFI_CMD_ADD_NETWORK)

NET_MGMT_DEFINE_REQUEST_HANDLER(NET_REQUEST_WIFI_ADD_NETWORK);

#define NET_REQUEST_WIFI_CLEAR_NETWORKS				\
	(_NET_WIFI_BASE | NET_REQUEST_WIFI_CMD_CLEAR_NETWORKS)

NET_MGMT_DEFINE_REQUEST_HANDLER(NET_REQUEST_WIFI_CLEAR_NETWORKS);
