name: Documentation Build

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - 'v*-branch'
    paths:
      - '.github/workflows/docbuild.yml'
      - '**.rst'
      - '**/Kconfig'
      - '**/sample.yaml'
      - 'doc/**'
      - 'applications/**'
      - 'include/**'
      - 'lib/**'
      - 'doc/requirements.txt'
      - 'scripts/tools-versions-*.yml'
      - 'west.yml'
  push:
    branches:
      - main
      - 'v*-branch'
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-24.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout sources
        uses: nrfconnect/action-checkout-west-update@main
        with:
          git-fetch-depth: 0

      - name: cache-pip
        uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf # v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-doc-pip

      - name: Install packages
        run: |
          sudo apt update
          sudo apt-get install -y ninja-build mscgen plantuml pipx python3-venv python3-wheel python3-setuptools clang sqlite3
          sudo snap install yq
          DOXYGEN_VERSION=$(yq ".doxygen.version" ./ncs/nrf/scripts/tools-versions-linux.yml)
          wget --no-verbose "https://github.com/doxygen/doxygen/releases/download/Release_${DOXYGEN_VERSION//./_}/doxygen-${DOXYGEN_VERSION}.linux.bin.tar.gz"
          tar xf doxygen-${DOXYGEN_VERSION}.linux.bin.tar.gz
          echo "${PWD}/doxygen-${DOXYGEN_VERSION}/bin" >> $GITHUB_PATH

      - name: Install Python dependencies
        working-directory: ncs
        run: |
          pip3 install -r nrf/scripts/requirements-fixed.txt
          pip3 install -r nrf/doc/requirements.txt
          pip3 install git+https://github.com/maxd-nordic/doc-sphinx-ncs-theme.git@128f7aa4629ea63f835f2fa6241dfe4ba746d17e --ignore-installed

      - name: West zephyr-export
        working-directory: ncs
        run: |
          west zephyr-export

      - name: Build documentation
        working-directory: ncs/nrf
        run: |
          if [[ "${{ github.event_name }}" == "push" ]]; then
            BUILD_CONF="-DDTS_BINDINGS=ON -DHW_FEATURES=ON"
          fi

          cmake -GNinja -Bdoc/_build -Sdoc -DSPHINXOPTS_EXTRA="-q" ${BUILD_CONF}
          ninja -C doc/_build

      - name: Check version
        run: |
          VERSION_REGEX="^v([0-9a-zA-Z\.\-]+)$"
          if [[ ${GITHUB_REF#refs/tags/} =~ $VERSION_REGEX ]]; then
            VERSION=${BASH_REMATCH[1]}
          elif [[ ${GITHUB_REF#refs/heads/} == "main" ]]; then
            VERSION="latest"
          elif [[ "${{ github.event_name }}" == "pull_request" ]]; then
            VERSION="pr-${{ github.event.number }}"
          fi

          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Prepare legacy upload
        if: ${{ !contains(github.event.pull_request.labels.*.name, 'external') || contains(github.event.pull_request.labels.*.name, 'CI-trusted-author') }}
        working-directory: ncs/nrf
        run: |
          MONITOR="monitor_${{ github.run_id }}.txt"

          # Create documentation upload files
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            ARCHIVE="legacy-ncs-pr-${{ github.event.number }}.zip"
            echo "publish2 dev PR-${{ github.event.number }} ${ARCHIVE}" > "${MONITOR}"
            echo "${{ github.event.number }}" > pr.txt
          else
            if [ -z "${VERSION}" ]; then
              echo "Not a release or latest, skipping publish"
              exit 0
            fi

            ARCHIVE="legacy-ncs-${VERSION}.zip"
            echo "publish2 main ${VERSION} ${ARCHIVE}" > "${MONITOR}"
          fi

          cd doc/_build/html
          zip -rq "${ARCHIVE}" .
          mv "${ARCHIVE}" ../../../

      # - name: Build Docsets
      #   working-directory: ncs/nrf/doc/_build
      #   run: |
      #     mkdir docsets
      #     pipx run doc2dash -d docsets/ -n kconfig html/kconfig
      #     pipx run doc2dash -d docsets/ -n matter html/matter
      #     pipx run doc2dash -d docsets/ -n mcuboot html/mcuboot --index-page wrapper.html
      #     pipx run doc2dash -d docsets/ -n nrf html/nrf
      #     pipx run doc2dash -d docsets/ -n nrfxlib html/nrfxlib --index-page README.html
      #     pipx run doc2dash -d docsets/ -n nrfx html/nrfx
      #     pipx run doc2dash -d docsets/ -n tfm html/tfm
      #     pipx run doc2dash -d docsets/ -n zephyr html/zephyr

      # - name: Add docset icons
      #   working-directory: ncs/nrf/doc/
      #   run: |
      #     cp docset-logos/zephyr-logo.png _build/docsets/kconfig.docset/icon.png
      #     cp docset-logos/matter-logo.png _build/docsets/matter.docset/icon.png
      #     cp docset-logos/mcuboot-logo.png _build/docsets/mcuboot.docset/icon.png
      #     cp docset-logos/nordic-logo.png _build/docsets/nrf.docset/icon.png
      #     cp docset-logos/nordic-logo.png _build/docsets/nrfxlib.docset/icon.png
      #     cp docset-logos/nordic-logo.png _build/docsets/nrfx.docset/icon.png
      #     cp docset-logos/tfm-logo.png _build/docsets/tfm.docset/icon.png
      #     cp docset-logos/zephyr-logo.png _build/docsets/zephyr.docset/icon.png

      # - name: Fix KConfig docset
      #   working-directory: ncs/nrf/doc/_build/docsets/kconfig.docset/Contents/Resources/Documents
      #   run: python3 ../../../../../../_scripts/rebuild_kconfig_index.py

      # - name: Filter out group elements from Zephyr docset
      #   working-directory: ncs/nrf/doc/_build/docsets/zephyr.docset/Contents/Resources/Documents
      #   run: python3 ../../../../../../_scripts/filter_docset_index.py

      # - name: Filter out group elements from nrf docset
      #   working-directory: ncs/nrf/doc/_build/docsets/nrf.docset/Contents/Resources/Documents
      #   run: python3 ../../../../../../_scripts/filter_docset_index.py

      # - name: Filter out group elements from nrfx docset
      #   working-directory: ncs/nrf/doc/_build/docsets/nrfx.docset/Contents/Resources/Documents
      #   run: python3 ../../../../../../_scripts/filter_docset_index.py

      # - name: Filter out group elements from nrfxlib docset
      #   working-directory: ncs/nrf/doc/_build/docsets/nrfxlib.docset/Contents/Resources/Documents
      #   run: python3 ../../../../../../_scripts/filter_docset_index.py

      # - name: Fix links between docsets
      #   working-directory: ncs/nrf/doc/_build/docsets/
      #   run: |
      #     find . -type f -name "*.html" -exec sed -i -E 's#(a|class=\"reference external\") href="([^"]*)\.\./nrfxlib/([^"]*)"#\1 href=\"\2../../../../../nrfxlib.docset/Contents/Resources/Documents/\3"#g' {} +
      #     find . -type f -name "*.html" -exec sed -i -E 's#(a|class=\"reference external\") href="([^"]*)\.\./mcuboot/([^"]*)"#\1 href=\"\2../../../../../mcuboot.docset/Contents/Resources/Documents/\3"#g' {} +
      #     find . -type f -name "*.html" -exec sed -i -E 's#(a|class=\"reference external\") href="([^"]*)\.\./matter/([^"]*)"#\1 href=\"\2../../../../../matter.docset/Contents/Resources/Documents/\3"#g' {} +
      #     find . -type f -name "*.html" -exec sed -i -E 's#(a|class=\"reference external\") href="([^"]*)\.\./nrfx/([^"]*)"#\1 href=\"\2../../../../../nrfx.docset/Contents/Resources/Documents/\3"#g' {} +
      #     find . -type f -name "*.html" -exec sed -i -E 's#(a|class=\"reference external\") href="([^"]*)\.\./kconfig/([^"]*)"#\1 href=\"\2../../../../../kconfig.docset/Contents/Resources/Documents/\3"#g' {} +
      #     find . -type f -name "*.html" -exec sed -i -E 's#(a|class=\"reference external\") href="([^"]*)\.\./nrf/([^"]*)"#\1 href=\"\2../../../../../nrf.docset/Contents/Resources/Documents/\3"#g' {} +
      #     find . -type f -name "*.html" -exec sed -i -E 's#(a|class=\"reference external\") href="([^"]*)\.\./zephyr/([^"]*)"#\1 href=\"\2../../../../../zephyr.docset/Contents/Resources/Documents/\3"#g' {} +
      #     find . -type f -name "*.html" -exec sed -i -E 's#(a|class=\"reference external\") href="([^"]*)\.\./tfm/([^"]*)"#\1 href=\"\2../../../../../tfm.docset/Contents/Resources/Documents/\3"#g' {} +

      - name: Compress Docsets
        working-directory: ncs/nrf/doc/_build
        run: tar czf html.tar.xz html/

      - name: Upload Docsets
        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4
        with:
          name: docsets
          path: ncs/nrf/doc/_build/html.tar.xz

      - name: Store
        if: ${{ !contains(github.event.pull_request.labels.*.name, 'external') || contains(github.event.pull_request.labels.*.name, 'CI-trusted-author') }}
        uses: actions/upload-artifact@4cec3d8aa04e39d1a68397de0c4cd6fb9dce8ec1 # v4
        with:
          name: docs
          path: |
            ncs/nrf/*.zip
            ncs/nrf/monitor*.txt
            ncs/nrf/pr.txt
            ncs/nrf/comment.txt
